---
version: 3
images:
  base_image:
    name: rockylinux:9
dependencies:
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: amazon.aws
      - name: ansible.posix
      - name: ansible.windows
      - name: awx.awx
      - name: azure.azcollection
      - name: community.windows
      - name: community.vmware
      - name: kubernetes.core
      - name: google.cloud
      - name: openstack.cloud
      - name: ovirt.ovirt
      - name: theforeman.foreman
  system: |
    epel-release [platform:rpm]
    gcc [platform:rpm]
    gcc-c++ [platform:rpm]
    git-core [platform:rpm]
    git-lfs [platform:rpm]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    libcurl-devel [platform:rpm compile]
    podman-remote [platform:rpm]
    python3.9-devel [platform:rpm compile]
    python-unversioned-command [platform:rpm]
    rsync [platform:rpm]
    sshpass [platform:rpm]
    subversion [platform:dpkg]
    subversion [platform:rpm]
    unzip [platform:rpm]
  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pexpect>=4.5
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    python-daemon
    pywinrm[kerberos,credssp]
    pyyaml
    receptorctl
    six
    toml
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
